### ISSUE TITLE
Sleep time on WaitHelper could be configurable

### ISSUE THREAD

**Issue by kirederik** [pivotal-cf-experimental/ops_manager_ui_drivers#11]
We're using the opsmgr gem to trigger the installation on our PCF environments and this takes a while to complete. We have the log level set to Debug, and with a sleep interval of 0.5 seconds (the default) we are getting flooded with logs. For example:

![screen shot 2016-01-27 at 11 28 37](https://cloud.githubusercontent.com/assets/201163/12612164/bbbb49b4-c4e8-11e5-8c8a-ae664e8a63a4.png)

We think we've got a solution, by exposing a `OpsManagerUiDrivers::WaitHelper::sleep_interval` (similar with `OpsManagerUiDrivers::Logger.logger.level`). Would you be open to accepting a PR for this?

**Comment by aashah** [comment]
We're totally open to PRs. Otherwise, the work to do this is captured in the story that got created automatically. I'll prioritize the chore in any case.
