### ISSUE TITLE
Disable ICMP checks

### ISSUE THREAD

**Issue by cgfrost** [pivotal-cf-experimental/ops_manager_ui_drivers#18]
It is not possible to configure ops manager to have ICMP checks disabled. The field name is `icmp_checks_enabled` but it isn't used in the code. For example, in https://github.com/pivotal-cf-experimental/ops_manager_ui_drivers/blob/master/lib/ops_manager_ui_drivers/version17/ops_manager_director.rb#L47 I would expect to see some code for applying the `icmp_checks_enabled` value. Same for the other versions as well. This feature is needed in the Spring Cloud Services team to help us automate more of our CI.

**Comment by ctaymor** [comment]
I'll talk with product to prioritize this work, it doesn't seem very difficult. Alternatively, we do accept pull requests.

**Comment by ctaymor** [comment]
To be clear, are you using ops_manager_ui_drivers directly? The OpsManager team doesn't control OpsMgr, if that's what you're using.

**Comment by cgfrost** [comment]
We are using OpsMgr but we will either by pass it or get OpsMgr support for ICMP added.

**Comment by drich10** [comment]
Added as a part of the https://github.com/pivotal-cf-experimental/ops_manager_ui_drivers/tree/v2.24.0 release

**Comment by cgfrost** [comment]
Awesome stuff, thank you.
